name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # runs daily
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: 3D Contribution Graph
    steps:
      - uses: actions/checkout@v4
      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: Hamza-Shaukat078

      - name: Push to profile-3d-contrib branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: profile-3d-contrib
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
